language: node_js

# Caché establecemos el sitema de cahce que va a tener
cache:
  directories:
    - ~/.npm

# Le decimos la versión de Node con la que traaja.

node_js:
  - '14'

 # Es la profundidad a la que va a llegar
git:
  depth: 3

# Comando que ejecuta la compilación del tropyecto
script:
  - yarn build

# Preparamos el deploy con, un provider.

deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Realease"
  on:
    branch: master
    