# -*- coding: utf-8 -*-
"""ConectingDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5F9z2abkNgdjoljPMLYlJBKH7EtR5F1
"""

pip install psycopg2

import pandas as pd
import psycopg2
from sqlalchemy import create_engine

# Instance of engine
engine = create_engine('postgresql+psycopg2://dvdrental:ROOTETRX@127.0.0.1,pool_recycle=3600');
engine

# Connect to postgreSQL

db_conection = engine.connect();

# Aquí leería el data frame en teoría
df = pd.read_sql("select*from \"name_) ")
pd.set_option('display.expand_frame_repr',False);

